version: '3.7'
services:
  redis:
    image: "redis:7-alpine"
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  rails:
    platform: linux/x86_64
    build: ./ 
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0  # Point to the Redis container
    volumes:
      - .:/docker/app # add our local code to dockerfile

volumes:
  redis_data: